# Generated by Django 4.2.10 on 2025-07-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_users", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("teleops", "Teleops Internal"),
                    ("corporate", "Corporate"),
                    ("circle", "Circle"),
                    ("vendor", "Vendor"),
                    ("tenant", "Tenant"),
                ],
                default="tenant",
                max_length=20,
            ),
        ),
    ]
