# Generated by Django 5.2.4 on 2025-07-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_users', '0004_certificationtype_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent_department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='vendoroperationaldesignation',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RenameIndex(
            model_name='vendoroperationaldesignation',
            new_name='vendor_oper_departm_a44f49_idx',
            old_name='vendor_oper_departm_2416e3_idx',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
