# Generated by Django 4.2.10 on 2025-08-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0003_add_specification_columns"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="site",
            name="sites_town_9de435_idx",
        ),
        migrations.RemoveIndex(
            model_name="site",
            name="sites_cluster_aa2069_idx",
        ),
        migrations.RemoveField(
            model_name="site",
            name="access_instructions",
        ),
        migrations.RemoveField(
            model_name="site",
            name="district",
        ),
        migrations.RemoveField(
            model_name="site",
            name="elevation",
        ),
        migrations.RemoveField(
            model_name="site",
            name="landmark_description",
        ),
        migrations.RemoveField(
            model_name="site",
            name="safety_requirements",
        ),
        migrations.AlterField(
            model_name="site",
            name="address",
            field=models.TextField(blank=True, help_text="Site address"),
        ),
        migrations.AlterField(
            model_name="site",
            name="city",
            field=models.CharField(
                blank=True, help_text="Legacy: use town instead", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="cluster",
            field=models.CharField(
                help_text="Zone/operational cluster", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="contact_person",
            field=models.CharField(
                blank=True, help_text="On-site contact person", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="contact_phone",
            field=models.CharField(
                blank=True, help_text="Contact phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(
                blank=True, help_text="Legacy: use site_name instead", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="site_code",
            field=models.CharField(
                blank=True, help_text="Legacy site code", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="site_type",
            field=models.CharField(
                choices=[
                    ("tower", "Tower"),
                    ("data_center", "Data Center"),
                    ("exchange", "Exchange"),
                    ("substation", "Substation"),
                    ("office", "Office"),
                    ("warehouse", "Warehouse"),
                    ("other", "Other"),
                ],
                default="tower",
                help_text="Type of site",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="town",
            field=models.CharField(help_text="Town/city location", max_length=100),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["town", "cluster"], name="sites_town_de41f2_idx"
            ),
        ),
    ]
