# Generated by Django 4.2.10 on 2025-08-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0005_bulkuploadjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkuploadjob",
            name="detailed_errors",
            field=models.JSONField(
                blank=True,
                help_text="Detailed error list for each failed row",
                null=True,
            ),
        ),
    ]
