# Generated by Django 5.2.4 on 2025-09-06 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0010_create_bulk_task_creation_job"),
        ("sites", "0006_bulkuploadjob_detailed_errors"),
        ("projects", "0014_fix_inventory_unique_constraints"),
        ("teams", "__first__"),
        ("tenants", "0032_transfer_circle_vendor_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create Task model
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        help_text="Business task identifier", max_length=50
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("installation", "Installation"),
                            ("maintenance", "Maintenance"),
                            ("dismantling", "Dismantling"),
                            ("survey", "Survey"),
                            ("audit", "Audit"),
                            ("repair", "Repair"),
                            ("upgrade", "Upgrade"),
                            ("testing", "Testing"),
                            ("commissioning", "Commissioning"),
                            ("rf_survey", "RF Survey"),
                            ("emf_survey", "EMF Survey"),
                            ("rfi_survey", "RFI Survey"),
                            ("transportation", "Transportation"),
                            ("packaging", "Packaging"),
                            ("deviation_email", "Deviation Email"),
                            ("rsa", "RSA"),
                        ],
                        default="maintenance",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("allocated", "Allocated"),
                            ("in_progress", "In Progress"),
                            ("equipment_verification", "Equipment Verification"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("on_hold", "On Hold"),
                            ("failed", "Failed"),
                            ("rework_required", "Rework Required"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "equipment_verification_required",
                    models.BooleanField(default=False),
                ),
                (
                    "equipment_verification_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="not_required",
                        max_length=20,
                    ),
                ),
                (
                    "equipment_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_site",
                    models.ForeignKey(
                        "sites.Site",
                        on_delete=models.CASCADE,
                        related_name="primary_tasks",
                        help_text="Primary site for this task",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        "tenants.Tenant",
                        on_delete=models.CASCADE,
                        related_name="tasks",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        "projects.Project",
                        on_delete=models.CASCADE,
                        related_name="tasks",
                        null=True,
                        blank=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        settings.AUTH_USER_MODEL,
                        on_delete=models.SET_NULL,
                        related_name="assigned_tasks",
                        null=True,
                        blank=True,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        settings.AUTH_USER_MODEL,
                        on_delete=models.SET_NULL,
                        related_name="supervised_tasks",
                        null=True,
                        blank=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        settings.AUTH_USER_MODEL,
                        on_delete=models.SET_NULL,
                        related_name="created_tasks",
                        null=True,
                        blank=True,
                    ),
                ),
                (
                    "equipment_verified_by",
                    models.ForeignKey(
                        settings.AUTH_USER_MODEL,
                        on_delete=models.SET_NULL,
                        related_name="verified_equipment_tasks",
                        null=True,
                        blank=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-created_at"],
                "unique_together": {("tenant", "task_id")},
            },
        ),
    ]