# Generated by Django 5.2.4 on 2025-09-06 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0011_auto_20250906_1446"),
        ("projects", "0014_fix_inventory_unique_constraints"),
        ("teams", "__first__"),
        ("tenants", "0032_transfer_circle_vendor_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create TaskAllocation model
        migrations.CreateModel(
            name="TaskAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[
                            ("vendor", "Vendor"),
                            ("internal_team", "Internal Team"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("allocated", "Allocated"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="allocated",
                        max_length=20,
                    ),
                ),
                ("allocation_notes", models.TextField(blank=True)),
                (
                    "estimated_duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        "Task",
                        on_delete=models.CASCADE,
                        related_name="allocations",
                    ),
                ),
                (
                    "vendor_relationship",
                    models.ForeignKey(
                        "projects.ProjectVendor",
                        on_delete=models.CASCADE,
                        related_name="task_allocations",
                        null=True,
                        blank=True,
                    ),
                ),
                (
                    "internal_team",
                    models.ForeignKey(
                        "teams.Team",
                        on_delete=models.CASCADE,
                        related_name="task_allocations",
                        null=True,
                        blank=True,
                    ),
                ),
                (
                    "allocated_by",
                    models.ForeignKey(
                        settings.AUTH_USER_MODEL,
                        on_delete=models.SET_NULL,
                        related_name="allocated_tasks",
                        null=True,
                        blank=True,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        settings.AUTH_USER_MODEL,
                        on_delete=models.SET_NULL,
                        related_name="updated_task_allocations",
                        null=True,
                        blank=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Allocation",
                "verbose_name_plural": "Task Allocations",
                "ordering": ["-created_at"],
            },
        ),
    ]