# Generated by Django 4.2.10 on 2025-09-09 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0012_auto_20250906_1448"),
    ]

    operations = []
