# Generated by Django 4.2.10 on 2025-09-09 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0010_add_task_type_to_taskfromflow"),
        ("tasks", "0013_auto_20250910_0200"),
    ]

    operations = []
