# Generated by Django 4.2.10 on 2025-09-09 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0016_fix_taskallocation_foreign_key"),
        ("tasks", "0017_remove_unnecessary_taskallocation_columns"),
    ]

    operations = []
