# Generated by Django 4.2.10 on 2025-09-10 12:00

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0019_update_allocation_status_choices"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_type', models.CharField(choices=[('vendor', 'Vendor'), ('internal_team', 'Internal Team')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deallocated', 'Deallocated'), ('in_issue', 'In Issue')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('allocation_reference', models.CharField(blank=True, max_length=100)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allocation_notes', models.TextField(blank=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='tasks.taskfromflow')),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_allocations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_allocations', to=settings.AUTH_USER_MODEL)),
                ('vendor_relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_allocations', to='tenants.clientvendorrelationship')),

            ],
            options={
                'db_table': 'tasks_taskallocation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubActivityAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deallocated', 'Deallocated'), ('in_issue', 'In Issue')], default='pending', max_length=20)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actual_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_activity_allocations', to='tasks.taskallocation')),
                ('sub_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='tasks.tasksubactivity')),
            ],
            options={
                'db_table': 'tasks_subactivityallocation',
                'ordering': ['sub_activity__sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='AllocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('allocated', 'Allocated'), ('deallocated', 'Deallocated'), ('reallocated', 'Reallocated'), ('progress_updated', 'Progress Updated'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deallocated', 'Deallocated'), ('in_issue', 'In Issue')], max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deallocated', 'Deallocated'), ('in_issue', 'In Issue')], max_length=20, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.taskallocation')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_allocationhistory',
                'ordering': ['-created_at'],
            },
        ),
    ]
