# Generated by Django 4.2.10 on 2025-09-10 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0021_fix_task_field_nullable"),
    ]

    operations = [
        # First, drop any foreign key constraints that reference the tasks table
        migrations.RunSQL(
            "ALTER TABLE task_comments DROP CONSTRAINT IF EXISTS task_comments_task_id_774b925c_fk_tasks_id;",
            reverse_sql="-- Cannot reverse dropping constraint",
        ),
        # Drop any other potential constraints
        migrations.RunSQL(
            "ALTER TABLE task_comments DROP CONSTRAINT IF EXISTS task_comments_task_id_fkey;",
            reverse_sql="-- Cannot reverse dropping constraint",
        ),
        # Now drop the legacy tasks table
        migrations.RunSQL(
            "DROP TABLE IF EXISTS tasks CASCADE;",
            reverse_sql="-- Cannot reverse dropping the legacy tasks table",
        ),
    ]
