# Generated by Django 4.2.10 on 2025-09-15 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0026_create_allocation_history_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskallocation',
            name='scheduled_start',
        ),
        migrations.RemoveField(
            model_name='taskallocation',
            name='scheduled_end',
        ),
        migrations.RemoveField(
            model_name='taskallocation',
            name='estimated_duration_hours',
        ),
        migrations.RemoveField(
            model_name='taskallocation',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='taskallocation',
            name='actual_start',
        ),
        migrations.RemoveField(
            model_name='taskallocation',
            name='actual_end',
        ),
        migrations.RemoveField(
            model_name='taskallocation',
            name='actual_duration_hours',
        ),
        migrations.RemoveField(
            model_name='taskallocation',
            name='actual_cost',
        ),
    ]
