# Generated by Django 4.2.10 on 2025-10-03 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0032_transfer_circle_vendor_data"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("tenant", "name")},
        ),
        migrations.RemoveField(
            model_name="team",
            name="team_code",
        ),
    ]
