# Generated by Django 4.2.10 on 2025-08-11 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0004_remove_site_sites_town_9de435_idx_and_more"),
        ("projects", "0007_add_current_version_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_project_sites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_sites",
                        to="projects.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_projects",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "db_table": "project_sites",
                "indexes": [
                    models.Index(
                        fields=["project"], name="project_sit_project_e4da02_idx"
                    ),
                    models.Index(
                        fields=["site"], name="project_sit_site_id_b07dcb_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="project_sit_is_acti_3c121f_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="projectsite",
            constraint=models.UniqueConstraint(
                fields=("project", "site"), name="unique_site_per_project"
            ),
        ),
    ]
