# Generated by Django 4.2.10 on 2025-08-12 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipment", "0001_initial"),
        ("tenants", "0032_transfer_circle_vendor_data"),
        ("projects", "0008_projectsite_projectsite_unique_site_per_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInventoryPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("installation", "Installation"),
                            ("dismantle", "Dismantle"),
                        ],
                        default="dismantle",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_project_inventory_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_inventory_plans",
                        to="projects.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_inventory_plans",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "project_inventory_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectInventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planned_qty", models.PositiveIntegerField(default=0)),
                ("uom", models.CharField(default="Unit", max_length=32)),
                (
                    "equipment_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_inventory_items",
                        to="equipment.equipmentinventoryitem",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="projects.projectinventoryplan",
                    ),
                ),
            ],
            options={
                "db_table": "project_inventory_items",
            },
        ),
        migrations.CreateModel(
            name="ProjectSiteInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=128)),
                ("serial_normalized", models.CharField(editable=False, max_length=128)),
                ("remarks", models.TextField(blank=True)),
                ("equipment_name", models.CharField(blank=True, max_length=255)),
                ("equipment_model", models.CharField(blank=True, max_length=255)),
                (
                    "site_id_business",
                    models.CharField(
                        blank=True,
                        help_text="Original Site ID from upload for traceability",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_project_site_inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site_planned_serials",
                        to="equipment.equipmentinventoryitem",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_inventory",
                        to="projects.projectinventoryplan",
                    ),
                ),
                (
                    "project_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_inventory",
                        to="projects.projectsite",
                    ),
                ),
            ],
            options={
                "db_table": "project_site_inventory",
                "indexes": [
                    models.Index(
                        fields=["plan", "project_site"],
                        name="project_sit_plan_id_d40c99_idx",
                    ),
                    models.Index(
                        fields=["plan", "equipment_item"],
                        name="project_sit_plan_id_26eb1f_idx",
                    ),
                    models.Index(
                        fields=["serial_normalized"],
                        name="project_sit_serial__3597d6_idx",
                    ),
                    models.Index(
                        fields=["equipment_item"], name="project_sit_equipme_098f46_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="project_sit_created_bcbb25_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="projectsiteinventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("plan", "project_site", "serial_normalized"),
                name="unique_serial_per_plan_site_active",
            ),
        ),
        migrations.AddIndex(
            model_name="projectinventoryplan",
            index=models.Index(
                fields=["tenant", "project"], name="project_inv_tenant__954bb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectinventoryplan",
            index=models.Index(
                fields=["project_type"], name="project_inv_project_aee775_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectinventoryitem",
            index=models.Index(fields=["plan"], name="project_inv_plan_id_88b0ce_idx"),
        ),
        migrations.AddIndex(
            model_name="projectinventoryitem",
            index=models.Index(
                fields=["equipment_item"], name="project_inv_equipme_be96e5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectinventoryitem",
            constraint=models.UniqueConstraint(
                fields=("plan", "equipment_item"), name="unique_equipment_item_per_plan"
            ),
        ),
    ]
