# Generated by Django 4.2.10 on 2025-08-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_projectinventoryplan_projectinventoryitem_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="projectsiteinventory",
            name="unique_serial_per_plan_site_active",
        ),
        migrations.AddField(
            model_name="projectsiteinventory",
            name="equipment_material_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="projectsiteinventory",
            name="project_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_inventory",
                to="projects.projectsite",
            ),
        ),
        migrations.AddIndex(
            model_name="projectsiteinventory",
            index=models.Index(
                fields=["plan", "site_id_business"],
                name="project_sit_plan_id_092d97_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectsiteinventory",
            index=models.Index(
                fields=["plan", "equipment_material_code"],
                name="project_sit_plan_id_b4045e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectsiteinventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("project_site__isnull", False)
                ),
                fields=("plan", "project_site", "serial_normalized"),
                name="uniq_serial_plan_site_linked",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectsiteinventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("project_site__isnull", True)
                ),
                fields=("plan", "site_id_business", "serial_normalized"),
                name="uniq_serial_plan_business_site_unlinked",
            ),
        ),
    ]
