# Generated by Django 4.2.10 on 2025-08-13 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0032_transfer_circle_vendor_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "projects",
            "0010_remove_projectsiteinventory_unique_serial_per_plan_site_active_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invite_email", models.EmailField(max_length=255)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                            ("discarded", "Discarded"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_vendor_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_vendor_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_invitations",
                        to="projects.project",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_invitations",
                        to="tenants.clientvendorrelationship",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_invitations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Invitation",
                "verbose_name_plural": "Vendor Invitations",
                "db_table": "vendor_invitations",
                "ordering": ["-invited_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "project"],
                        name="vendor_invi_tenant__31b382_idx",
                    ),
                    models.Index(
                        fields=["relationship"], name="vendor_invi_relatio_73d023_idx"
                    ),
                    models.Index(
                        fields=["status"], name="vendor_invi_status_5347df_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="vendor_invi_expires_bf78ca_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_notes", models.TextField(blank=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("hold", "On Hold"),
                            ("suspended", "Suspended"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_project_vendors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_vendors",
                        to="projects.project",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_links",
                        to="tenants.clientvendorrelationship",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_vendors",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "vendor_tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="as_vendor_project_links",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Vendor",
                "verbose_name_plural": "Project Vendors",
                "db_table": "project_vendors",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "project"],
                        name="project_ven_tenant__d3399d_idx",
                    ),
                    models.Index(
                        fields=["relationship"], name="project_ven_relatio_1da879_idx"
                    ),
                    models.Index(
                        fields=["vendor_tenant"], name="project_ven_vendor__326db2_idx"
                    ),
                    models.Index(
                        fields=["status"], name="project_ven_status_8905bd_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="projectvendor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "removed"), _negated=True),
                fields=("project", "relationship"),
                name="uniq_active_project_vendor_per_relationship",
            ),
        ),
    ]
