# Generated by Django 4.2.10 on 2025-07-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantuserprofile",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Employee", "Employee"),
                    ("Contractor", "Contractor"),
                    ("Consultant", "Consultant"),
                    ("Vendor", "Vendor"),
                ],
                default="Employee",
                max_length=20,
            ),
        ),
    ]
