# Generated by Django 4.2.10 on 2025-07-18 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_tenantuserprofile_employment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantuserprofile",
            name="employment_type",
        ),
    ]
