# Generated by Django 4.2.10 on 2025-07-18 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_remove_tenantuserprofile_employment_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tenant",
            name="tenants_organiz_be8e2b_idx",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="organization_code",
        ),
    ]
