# Generated by Django 4.2.10 on 2025-07-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_remove_tenant_tenants_organiz_be8e2b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circlevendorrelationship",
            name="vendor_code",
            field=models.CharField(
                help_text="Client-generated vendor code (from client's existing vendor management system)",
                max_length=100,
            ),
        ),
    ]
