# Generated by Django 4.2.10 on 2025-07-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_circlevendorrelationship_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinvitation',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantinvitation',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ] 