# Generated by Django 4.2.10 on 2025-07-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0008_alter_tenant_registration_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="equipment_capabilities",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="specialization",
        ),
        migrations.AlterField(
            model_name="tenant",
            name="coverage_areas",
            field=models.JSONField(
                default=list, help_text="Array of circle IDs/regions"
            ),
        ),
    ]
