# Generated by Django 4.2.10 on 2025-07-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0011_tenantuserprofile_employment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="circlevendorrelationship",
            name="contact_person_name",
            field=models.CharField(
                blank=True,
                help_text="Contact person name for vendor invitation",
                max_length=255,
            ),
        ),
    ]
