# Generated by Django 4.2.10 on 2025-07-22 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0013_remove_redundant_invitation_fields"),
    ]

    operations = []
