# Generated by Django 5.2.4 on 2025-07-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_designation_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprehensivedesignation',
            name='certifications_required',
            field=models.JSONField(default=dict, help_text='Required certifications for field positions: {farmtocli: true, fat: false, medical: true}'),
        ),
        migrations.AddField(
            model_name='comprehensivedesignation',
            name='designation_type',
            field=models.CharField(choices=[('field', 'Field'), ('non_field', 'Non-Field')], default='non_field', help_text='Whether this is a field or non-field designation', max_length=20),
        ),
    ]
