# Generated by Django 5.2.4 on 2025-07-25 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0023_tenantdepartment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenantdesignation",
            options={
                "ordering": ["designation_level", "designation_name"],
                "verbose_name": "Tenant Designation",
                "verbose_name_plural": "Tenant Designations",
            },
        ),
        migrations.RenameIndex(
            model_name="tenantdesignation",
            new_name="tenant_desi_tenant__042481_idx",
            old_name="comprehensi_tenant__57ca21_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantdesignation",
            new_name="tenant_desi_tenant__7d94e8_idx",
            old_name="comprehensi_tenant__85cd21_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantdesignation",
            new_name="tenant_desi_designa_a904a7_idx",
            old_name="comprehensi_designa_08f362_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantdesignation",
            new_name="tenant_desi_parent__36fe6a_idx",
            old_name="comprehensi_parent__16b00b_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantdesignation",
            new_name="tenant_desi_is_acti_c09c93_idx",
            old_name="comprehensi_is_acti_74dfa3_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantdesignation",
            new_name="tenant_desi_is_syst_84890c_idx",
            old_name="comprehensi_is_syst_9d9de1_idx",
        ),
        migrations.AlterModelTable(
            name="tenantdesignation",
            table="tenant_designations",
        ),
    ]
