# Generated by Django 5.2.4 on 2025-07-26 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0025_rename_tables_to_tenant_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdesignation',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department', help_text='Department this designation belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='tenants.tenantdepartment'),
        ),
    ]
