# Generated by Django 5.2.4 on 2025-07-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0026_alter_tenantdesignation_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionregistry',
            name='business_template',
            field=models.CharField(choices=[('view_only', 'View-Only Access'), ('contributor', 'Contributor/Editor'), ('creator_only', 'Creator Only'), ('full_access', 'Full Access/Administrator'), ('custom', 'Custom Permission')], default='custom', help_text='Business-friendly template used to create this permission', max_length=50),
        ),
    ]
