# Generated by Manual Creation on 2025-07-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0027_add_business_template_to_permission_registry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionregistry',
            name='action_type',
        ),
    ] 