# Generated by Manual Creation on 2025-07-27

from django.db import migrations


def fix_permission_audit_entries(apps, schema_editor):
    """Fix existing audit trail entries to use 'permission' entity type instead of 'system'."""
    PermissionAuditTrail = apps.get_model('tenants', 'PermissionAuditTrail')
    PermissionRegistry = apps.get_model('tenants', 'PermissionRegistry')
    
    # Find audit entries with entity_type='system' that are actually permission-related
    system_entries = PermissionAuditTrail.objects.filter(entity_type='system')
    
    updated_count = 0
    for entry in system_entries:
        try:
            # Check if the entity_id corresponds to a permission
            if PermissionRegistry.objects.filter(id=entry.entity_id).exists():
                entry.entity_type = 'permission'
                entry.save()
                updated_count += 1
        except Exception as e:
            # Skip entries that can't be processed
            continue
    
    print(f"Updated {updated_count} audit trail entries from 'system' to 'permission' entity type")


def reverse_fix_permission_audit_entries(apps, schema_editor):
    """Reverse the fix by changing entity_type back to 'system'."""
    PermissionAuditTrail = apps.get_model('tenants', 'PermissionAuditTrail')
    PermissionRegistry = apps.get_model('tenants', 'PermissionRegistry')
    
    # Find audit entries with entity_type='permission' 
    permission_entries = PermissionAuditTrail.objects.filter(entity_type='permission')
    
    for entry in permission_entries:
        try:
            # Check if the entity_id corresponds to a permission and change back to system
            if PermissionRegistry.objects.filter(id=entry.entity_id).exists():
                entry.entity_type = 'system'
                entry.save()
        except Exception as e:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0028_remove_action_type_from_permission_registry'),
    ]

    operations = [
        migrations.RunPython(
            fix_permission_audit_entries,
            reverse_fix_permission_audit_entries
        ),
    ] 