# Generated by Django 4.2.10 on 2025-07-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0029_fix_existing_permission_audit_entries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionregistry",
            name="resource_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("project", "Project Management"),
                    ("task", "Task Management"),
                    ("site", "Site Management"),
                    ("user", "User Management"),
                    ("deviation", "Deviation Management"),
                    ("report", "Reporting & Analytics"),
                    ("compliance", "Compliance Management"),
                    ("vendor", "Vendor Management"),
                    ("asset", "Asset Management"),
                    ("document", "Document Management"),
                    ("audit", "Audit & Logging"),
                    ("system", "System Administration"),
                    ("workflow", "Workflow Management"),
                    ("notification", "Notification Management"),
                    ("rbac", "RBAC Management"),
                    ("custom", "Custom Resource"),
                ],
                help_text="Application feature/module this permission controls",
                max_length=50,
            ),
        ),
    ]
