# Generated by Django 5.2.4 on 2025-08-01 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0030_alter_permissionregistry_resource_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientVendorRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_code",
                    models.CharField(
                        help_text="Client-generated vendor code (from client's existing vendor management system)",
                        max_length=100,
                    ),
                ),
                (
                    "contact_person_name",
                    models.CharField(
                        blank=True,
                        help_text="Contact person name for vendor invitation",
                        max_length=255,
                    ),
                ),
                (
                    "performance_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("Client_Vendor", "Client Vendor"),
                            ("Partnership", "Partnership"),
                            ("Subcontractor", "Subcontractor"),
                        ],
                        default="Client_Vendor",
                        max_length=50,
                    ),
                ),
                (
                    "relationship_status",
                    models.CharField(
                        choices=[
                            ("Client_Invitation_Sent", "Client Invitation Sent"),
                            ("Active", "Active"),
                            ("Suspended", "Suspended"),
                            ("Terminated", "Terminated"),
                            ("Expired", "Expired"),
                        ],
                        default="Client_Invitation_Sent",
                        max_length=50,
                    ),
                ),
                (
                    "vendor_verification_status",
                    models.CharField(
                        choices=[
                            ("Independent", "Independent"),
                            ("Pending_Verification", "Pending Verification"),
                            ("Verified", "Verified"),
                            ("Verification_Rejected", "Verification Rejected"),
                        ],
                        default="Independent",
                        help_text="Vendor verification status for this client relationship",
                        max_length=50,
                    ),
                ),
                (
                    "vendor_permissions",
                    models.JSONField(
                        default=dict, help_text="Permissions vendor has for circle data"
                    ),
                ),
                ("communication_allowed", models.BooleanField(default=True)),
                (
                    "contact_access_level",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Full", "Full"),
                            ("Restricted", "Restricted"),
                            ("None", "None"),
                        ],
                        default="Basic",
                        max_length=50,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_client_vendor_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_vendor_relationships",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "vendor_tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_client_relationships",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Vendor Relationship",
                "verbose_name_plural": "Client Vendor Relationships",
                "db_table": "client_vendor_relationships",
            },
        ),
        migrations.DeleteModel(
            name="CircleVendorRelationship",
        ),
        migrations.AddIndex(
            model_name="clientvendorrelationship",
            index=models.Index(
                fields=["client_tenant"], name="client_vend_client__973c4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientvendorrelationship",
            index=models.Index(
                fields=["vendor_tenant"], name="client_vend_vendor__9b60d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientvendorrelationship",
            index=models.Index(
                fields=["vendor_code"], name="client_vend_vendor__6c2326_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientvendorrelationship",
            index=models.Index(
                fields=["relationship_status"], name="client_vend_relatio_e1d348_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientvendorrelationship",
            index=models.Index(
                fields=["is_active"], name="client_vend_is_acti_8b8911_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientvendorrelationship",
            unique_together={
                ("client_tenant", "vendor_code"),
                ("client_tenant", "vendor_tenant"),
            },
        ),
    ]
