# Generated by Django 4.2.10 on 2025-07-19 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teleops_internal_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internalprofile",
            options={
                "ordering": ["display_name", "user__email"],
                "verbose_name": "Internal Profile",
                "verbose_name_plural": "Internal Profiles",
            },
        ),
        migrations.AlterField(
            model_name="internalprofile",
            name="access_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("read_only", "Read Only"),
                    ("standard", "Standard"),
                    ("admin", "Admin"),
                    ("", "None"),
                ],
                default="",
                help_text="Access level for internal portal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="internalprofile",
            name="department",
            field=models.CharField(
                blank=True, help_text="Department or team", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="internalprofile",
            name="display_name",
            field=models.CharField(
                blank=True, help_text="Display name for internal portal", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="internalprofile",
            name="employee_id",
            field=models.CharField(
                blank=True,
                help_text="Employee identification number",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="internalprofile",
            name="last_login",
            field=models.DateTimeField(
                blank=True, help_text="Last login timestamp", null=True
            ),
        ),
        migrations.AlterField(
            model_name="internalprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Contact phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="internalprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                help_text="Profile photo for internal portal",
                null=True,
                upload_to="profile_photos/",
            ),
        ),
        migrations.AlterField(
            model_name="internalprofile",
            name="reporting_manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct reporting manager",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="teleops_internal_users.internalprofile",
            ),
        ),
        migrations.AlterField(
            model_name="internalprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("super_admin", "Super Administrator"),
                    ("operations_manager", "Operations Manager"),
                    ("support_staff", "Support Staff"),
                    ("", "None"),
                ],
                default="",
                help_text="Internal role designation",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="internalprofile",
            name="user",
            field=models.OneToOneField(
                help_text="Associated user account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internal_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="internalprofile",
            index=models.Index(fields=["role"], name="internal_pr_role_87d6d5_idx"),
        ),
        migrations.AddIndex(
            model_name="internalprofile",
            index=models.Index(
                fields=["access_level"], name="internal_pr_access__bb6178_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internalprofile",
            index=models.Index(
                fields=["department"], name="internal_pr_departm_c7d135_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internalprofile",
            index=models.Index(
                fields=["employee_id"], name="internal_pr_employe_a3430b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internalprofile",
            index=models.Index(
                fields=["created_at"], name="internal_pr_created_185f40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internalprofile",
            index=models.Index(
                fields=["last_login"], name="internal_pr_last_lo_29f4ef_idx"
            ),
        ),
    ]
